---

- name: Install OpenJDK 8 (Ubuntu)
  apt: name=openjdk-8-jre-headless state=present update_cache=yes
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install Zabbix (Ubuntu)
  apt: name=zabbix-agent state=present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install probe (Ubuntu)
  apt: name=occi-zabbix-probe state=present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install OpenJDK 8 (CentOS)
  yum: name=java-1.8.0-openjdk-headless state=present update_cache=yes
  become: true
  when: ansible_distribution == 'CentOS'

- name: Install Zabbix repository (CentOS)
  yum: name=http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm state=present
  become: true
  when: ansible_distribution == 'CentOS'

- name: Install Zabbix agent (CentOS)
  yum: name=zabbix-agent state=present
  become: true
  when: ansible_distribution == 'CentOS'

- name: Install probe (CentOS)
  yum: name=OCCIZabbixProbe state=present
  become: true
  when: ansible_distribution == 'CentOS'

- name: Configuration creation
  template: src=occiprobe.properties.j2 dest="{{ zabbix_config_location }}/occiprobe.properties"
